"""Adjustable engineering thresholds; these are not clinically validated cutoffs."""

LOWERED_ANGLE_MAX = 35.0
RAISED_ANGLE_MIN = 75.0
TARGET_ANGLE_MIN = 80.0
TARGET_ANGLE_MAX = 120.0
MIN_ANGLE_RANGE = 45.0
MIN_REP_DURATION_SEC = 0.8
MAX_REP_DURATION_SEC = 10.0
MIN_POSE_VISIBILITY = 0.5
MIN_VALID_FRAMES_RATIO = 0.45
MIN_POSE_DETECTED_FRAMES = 20
MIN_PHASE_FRAMES = 3
MIN_FRAMES_BETWEEN_REPS = 3
TEMPO_FAST_SEC = 1.1
TEMPO_INCONSISTENCY_RATIO = 0.35
TRUNK_COMPENSATION_ANGLE = 18.0
SHOULDER_HIKE_Y_DIFFERENCE = 0.055
