# Generated by Django 5.2.17 on 2026-09-12 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(max_length=128)),
                ('key', models.CharField(max_length=128)),
                ('scope', models.CharField(max_length=255)),
                ('fingerprint', models.CharField(max_length=64)),
                ('state', models.CharField(default='pending', max_length=16)),
                ('status_code', models.PositiveSmallIntegerField(null=True)),
                ('response', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('owner_id', 'key', 'scope'), name='unique_owned_submission')],
            },
        ),
    ]
