# Generated by Django 5.2.17 on 2026-09-14 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisJobRecord',
            fields=[
                ('job_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('owner_id', models.CharField(db_index=True, max_length=36)),
                ('exercise_id', models.CharField(max_length=64)),
                ('status', models.CharField(db_index=True, max_length=24)),
                ('outcome', models.CharField(max_length=24, null=True)),
                ('stage', models.CharField(max_length=64)),
                ('progress', models.PositiveSmallIntegerField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=0)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('error_code', models.CharField(max_length=128, null=True)),
                ('message', models.TextField(null=True)),
                ('http_status', models.PositiveSmallIntegerField(null=True)),
                ('result', models.JSONField(null=True)),
                ('engine_version', models.CharField(max_length=128, null=True)),
                ('model_version', models.CharField(max_length=128, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
