"""Conservative thresholds for the educational static balance MVP."""

MIN_BALANCE_DURATION_SEC = 3.0
TARGET_BALANCE_DURATION_SEC = 10.0
MIN_CRITICAL_VISIBILITY = 0.55

SWAY_RMS_REVIEW = 0.045
SWAY_MAX_REVIEW = 0.095
SWAY_VELOCITY_REVIEW = 0.12
TRUNK_LEAN_REVIEW_DEG = 12.0
PELVIS_TILT_REVIEW = 0.035
KNEE_VARIABILITY_REVIEW_DEG = 8.0
FOOT_ADJUSTMENT_REVIEW = 0.045
SINGLE_LEG_LIFT_THRESHOLD = 0.08

