"""Adjustable MVP engineering thresholds; not clinically validated limits."""

FLEXED_KNEE_ANGLE_MAX = 135.0
EXTENDED_KNEE_ANGLE_MIN = 155.0
FULL_EXTENSION_REFERENCE = 175.0
MIN_ANGLE_RANGE = 30.0
MIN_REP_DURATION_SEC = 0.7
MAX_REP_DURATION_SEC = 8.0
MIN_POSE_VISIBILITY = 0.50
MIN_VALID_FRAMES_RATIO = 0.45
MIN_POSE_DETECTED_FRAMES = 20
MIN_PHASE_FRAMES = 3
MIN_FRAMES_BETWEEN_REPS = 5
TEMPO_FAST_SEC = 1.0
TEMPO_INCONSISTENCY_RATIO = 0.30
TRUNK_COMPENSATION_ANGLE = 35.0

