"""Conservative gait-analysis reference bands for the educational MVP."""

MIN_GAIT_CYCLES = 2
MIN_FOOT_EXCURSION = 0.055
MIN_CRITICAL_VISIBILITY = 0.55

REFERENCE_STANCE_PERCENT = 60.0
REFERENCE_SWING_PERCENT = 40.0
STANCE_TOLERANCE_PERCENT = 12.0

CADENCE_MIN_STEPS_PER_MIN = 80.0
CADENCE_TARGET_LOW = 95.0
CADENCE_TARGET_HIGH = 125.0
CADENCE_MAX_STEPS_PER_MIN = 140.0

ASYMMETRY_REVIEW_THRESHOLD = 15.0
STRIDE_VARIABILITY_REVIEW_THRESHOLD = 0.18
MIN_KNEE_ROM_DEG = 20.0

