# Generated by Django 5.2.17 on 2026-09-13 23:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('legacy_id', models.BigIntegerField(null=True, unique=True)),
                ('username', models.CharField(max_length=64, null=True, unique=True)),
                ('email', models.CharField(max_length=320, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=120, null=True)),
                ('role', models.CharField(max_length=32)),
                ('is_active', models.BooleanField()),
                ('is_verified', models.BooleanField()),
                ('account_status', models.CharField(max_length=32)),
                ('is_protected', models.BooleanField()),
                ('token_version', models.IntegerField()),
                ('permissions_json', models.TextField()),
                ('email_verified_at', models.DateTimeField(null=True)),
                ('verification_token_hash', models.CharField(max_length=64, null=True, unique=True)),
                ('verification_token_expires', models.DateTimeField(null=True)),
                ('verification_sent_at', models.DateTimeField(null=True)),
                ('reset_password_token_hash', models.CharField(max_length=64, null=True, unique=True)),
                ('reset_password_expires', models.DateTimeField(null=True)),
                ('reset_password_sent_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('credential_owner', models.CharField(default='legacy', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='AccessSession',
            fields=[
                ('token_digest', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('token_version', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.account')),
            ],
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.BigIntegerField(null=True, unique=True)),
                ('consent_type', models.CharField(max_length=64)),
                ('accepted', models.BooleanField()),
                ('accepted_at', models.DateTimeField(null=True)),
                ('version', models.CharField(max_length=32)),
                ('notes', models.TextField(null=True)),
                ('policy_url', models.URLField(max_length=2048, null=True)),
                ('account', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to='identity.account')),
            ],
        ),
        migrations.CreateModel(
            name='IdentityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_id', models.CharField(max_length=36, null=True)),
                ('action', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField()),
                ('metadata', models.JSONField(default=dict)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.account')),
            ],
        ),
        migrations.CreateModel(
            name='IdentityOutbox',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=64)),
                ('aggregate_id', models.CharField(max_length=36)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField()),
                ('published_at', models.DateTimeField(null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('event_type', 'aggregate_id'), name='unique_identity_domain_request')],
            },
        ),
    ]
