# Generated by Django 5.2.17 on 2026-09-13 23:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataRightsRequest',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(max_length=24)),
                ('status', models.CharField(default='pending', max_length=24)),
                ('details', models.TextField(null=True)),
                ('requested_at', models.DateTimeField()),
                ('reviewed_at', models.DateTimeField(null=True)),
                ('reviewed_by_id', models.CharField(max_length=36, null=True)),
                ('review_reason', models.TextField(null=True)),
                ('retention_until', models.DateTimeField(null=True)),
                ('downstream_status', models.JSONField(default=dict)),
                ('completed_at', models.DateTimeField(null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.account')),
            ],
        ),
    ]
