"""Engineering defaults for sit-to-stand; not clinically validated thresholds."""

SITTING_KNEE_ANGLE_MAX = 110.0
SITTING_HIP_ANGLE_MAX = 120.0
STANDING_KNEE_ANGLE_MIN = 155.0
STANDING_HIP_ANGLE_MIN = 150.0
TRUNK_LEAN_WARNING_ANGLE = 35.0
EXCESSIVE_TRUNK_LEAN_ANGLE = 50.0
MIN_REP_DURATION_SEC = 1.0
MAX_REP_DURATION_SEC = 10.0
MIN_ANGLE_DELTA = 35.0
MIN_PHASE_FRAMES = 3
MIN_FRAMES_BETWEEN_REPS = 10
MIN_POSE_DETECTED_FRAMES = 30
MIN_POSE_DETECTION_RATE = 0.50
MIN_CRITICAL_LANDMARK_VISIBILITY = 0.50
MAX_MISSING_GAP_FRAMES = 2
