import { ArrowRight, CheckCircle2, KeyRound, ListChecks, LockKeyhole, LogOut, MailCheck, ShieldCheck, UserRound } from "lucide-react";

import { Button } from "../components/common/UI.jsx";
import { PageHeader } from "../components/layout/AppShell.jsx";
import { useAuth } from "../context/AuthContext.jsx";
import { useLocale } from "../i18n/LocaleContext.jsx";

export default function Profile({ onLogout, onNavigate }) {
  const { user, logout } = useAuth();
  const { t, pretty } = useLocale();
  async function signOut() { await logout(); onLogout?.(); }
  const permissions = user?.permissions || [];
  return <main className="mx-auto w-full max-w-5xl px-5 py-9 sm:px-8 lg:px-10">
    <PageHeader title={t("profile.title")} description={t("workspace.viewSecurity")} actions={<Button variant="secondary" onClick={signOut}><LogOut size={17} />{t("profile.logout")}</Button>} />
    <div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_320px]">
      <section className="rounded-xl border border-slate-200 bg-white" aria-labelledby="account-details-heading"><div className="border-b border-slate-200 p-6"><div className="flex items-center gap-4"><span className="grid h-14 w-14 place-items-center rounded-full bg-[#071b4a] text-white"><UserRound size={25} /></span><div><h2 id="account-details-heading" className="text-xl font-extrabold text-[#071b4a]">{user?.full_name || t("profile.developmentUser")}</h2><p className="mt-1 text-sm text-slate-500">{user?.email}</p></div></div></div><dl className="divide-y divide-slate-200 px-6"><div className="grid gap-1 py-5 sm:grid-cols-[180px_1fr]"><dt className="text-sm font-semibold text-slate-500">{t("common.username")}</dt><dd className="text-sm font-bold text-[#071b4a]">{user?.username}</dd></div><div className="grid gap-1 py-5 sm:grid-cols-[180px_1fr]"><dt className="text-sm font-semibold text-slate-500">{t("common.role")}</dt><dd className="text-sm font-bold text-[#071b4a]">{pretty(user?.role)}</dd></div><div className="grid gap-1 py-5 sm:grid-cols-[180px_1fr]"><dt className="text-sm font-semibold text-slate-500">{t("common.status")}</dt><dd className="inline-flex items-center gap-2 text-sm font-bold text-emerald-700"><CheckCircle2 size={17} />{pretty(user?.account_status || "active")}</dd></div><div className="grid gap-1 py-5 sm:grid-cols-[180px_1fr]"><dt className="text-sm font-semibold text-slate-500">{t("workspace.accountAccess")}</dt><dd className="inline-flex items-center gap-2 text-sm font-bold text-emerald-700"><MailCheck size={17} />{t("workspace.accessEnabled")}</dd></div></dl></section>
      <aside className="space-y-5"><section className="rounded-xl border border-slate-200 bg-white p-6"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-full bg-blue-50 text-blue-700"><ShieldCheck size={21} /></span><div><h2 className="font-extrabold text-[#071b4a]">{t("workspace.status")}</h2><p className="mt-1 text-xs text-slate-500">JWT sessions and role access</p></div></div><div className="mt-5 space-y-3 text-sm text-slate-600"><p className="flex items-center gap-2"><LockKeyhole size={16} className="text-emerald-700" />Protected routes enabled</p><p className="flex items-center gap-2"><KeyRound size={16} className="text-emerald-700" />Password recovery available</p>{user?.is_protected ? <p className="flex items-center gap-2"><ShieldCheck size={16} className="text-blue-700" />Protected account</p> : null}</div></section>{user?.role === "super_admin" ? <section className="overflow-hidden rounded-xl border border-blue-200 bg-gradient-to-br from-blue-50 to-white p-5"><span className="grid h-11 w-11 place-items-center rounded-xl bg-blue-600 text-white shadow-sm"><ListChecks size={21} /></span><h2 className="mt-4 text-base font-extrabold text-[#071b4a]">{t("workflow.title")}</h2><p className="mt-2 text-xs leading-5 text-slate-600">{t("profile.workflowDescription")}</p><Button className="mt-5 w-full" onClick={() => onNavigate?.("adminWorkflow")}>{t("profile.openWorkflow")}<ArrowRight className="rtl:rotate-180" size={16} /></Button></section> : null}<section className="rounded-xl border border-slate-200 bg-slate-50 p-5"><h2 className="text-sm font-extrabold text-[#071b4a]">Permissions</h2><p className="mt-2 text-xs leading-5 text-slate-500">{permissions.includes("*") ? "Full application authority" : permissions.length ? `${permissions.length} assigned permissions` : "Role-based application access"}</p></section></aside>
    </div>
  </main>;
}
