import AnalysisOptions from "../components/upload/AnalysisOptions.jsx";
import CameraGuide from "../components/upload/CameraGuide.jsx";
import UploadCard from "../components/upload/UploadCard.jsx";
import { Card } from "../components/common/UI.jsx";
import { PageHeader } from "../components/layout/AppShell.jsx";
import { exerciseById } from "../data/exercises.js";

export default function UploadSquat(props) {
  const names = { bodyweight_squat: "squat", sit_to_stand: "sit-to-stand", knee_extension: "knee extension", shoulder_abduction: "shoulder abduction", hip_abduction: "hip abduction" };
  const exercises = props.exercises || [];
  const selected = exerciseById(props.exercise, exercises);
  const supported = exercises.filter((item) => item.supported_in_app);
  const planned = exercises.filter((item) => !item.supported_in_app);
  return <main className="mx-auto w-full max-w-7xl px-6 py-12"><PageHeader eyebrow="Movement analyzer" title="Upload a movement video" description={`Choose a clear recording for the rule-based ${names[props.exercise]} analyzer.`} /><div className="grid items-start gap-6 lg:grid-cols-[1fr_380px]"><div className="space-y-5"><Card className="p-5"><label htmlFor="exercise-selector" className="text-sm font-bold text-clinical-ink">Exercise</label><p className="mt-1 text-xs text-slate-500">Select the movement shown in the recording. Manual selection remains primary.</p><select id="exercise-selector" aria-label="Exercise selector" className="mt-3 w-full rounded-xl border border-slate-200 bg-white px-3 py-3 text-sm font-semibold text-slate-800" value={props.exercise} disabled={props.isLoading} onChange={(event) => props.onExerciseChange(event.target.value)}><optgroup label="Supported">{supported.map((item) => <option key={item.exercise_id} value={item.exercise_id}>{item.display_name}</option>)}</optgroup><optgroup label="Planned — not available yet">{planned.map((item) => <option key={item.exercise_id} value={item.exercise_id} disabled>{item.display_name} — Planned</option>)}</optgroup></select><div className="mt-4 grid gap-3 rounded-xl bg-blue-50 p-4 text-sm sm:grid-cols-2"><div><p className="text-xs font-bold uppercase text-clinical-blue">Recommended view</p><p className="mt-1 text-slate-700">{selected.recommended_camera_view}</p></div><div><p className="text-xs font-bold uppercase text-clinical-blue">Required visibility</p><p className="mt-1 text-slate-700">{selected.required_landmarks?.join(", ")}</p></div><div><p className="text-xs font-bold uppercase text-clinical-blue">Instruction</p><p className="mt-1 text-slate-700">{selected.expected_movement_pattern}</p></div><div><p className="text-xs font-bold uppercase text-clinical-blue">Safety</p><p className="mt-1 text-slate-700">{selected.safety_notes}</p></div></div></Card><UploadCard {...props} /><AnalysisOptions exercise={props.exercise} value={props.options} onChange={props.onOptionsChange} disabled={props.isLoading} /></div><CameraGuide exercise={props.exercise} metadata={selected} /></div></main>;
}
