// Generated by scripts/generate_rebuild_contracts.py. Do not edit.
export interface AdherenceCreate {
  plan_item_id: string;
  scheduled_date: string;
  completion_status: "completed" | "partial" | "not_completed";
  pain_before?: number | null;
  pain_after?: number | null;
  difficulty?: number | null;
  fatigue?: number | null;
  perceived_exertion?: number | null;
  symptoms_changed?: boolean;
  stopped_due_to_symptoms?: boolean;
  symptom_flags?: Array<"pain_increase" | "dizziness" | "faintness" | "unusual_shortness_of_breath" | "chest_discomfort" | "new_numbness_or_weakness" | "instability" | "other">;
  safety_acknowledged?: boolean;
  note?: string | null;
  analysis_session_id?: string | null;
}
export interface AdherenceDetail {
  plan_item_id: string;
  scheduled_date: string;
  completion_status: "completed" | "partial" | "not_completed";
  pain_before?: number | null;
  pain_after?: number | null;
  difficulty?: number | null;
  fatigue?: number | null;
  perceived_exertion?: number | null;
  symptoms_changed?: boolean;
  stopped_due_to_symptoms?: boolean;
  symptom_flags?: Array<"pain_increase" | "dizziness" | "faintness" | "unusual_shortness_of_breath" | "chest_discomfort" | "new_numbness_or_weakness" | "instability" | "other">;
  safety_acknowledged?: boolean;
  note?: string | null;
  analysis_session_id?: string | null;
  adherence_id: string;
  patient_id: string;
  alert_created?: boolean;
  response_state: "not_assessed" | "within_reported_tolerance" | "clinical_follow_up";
  supportive_instruction: string;
  clinician_review_required: boolean;
  reviewed_at?: string | null;
  reviewed_by_user_id?: string | null;
  review_disposition?: string | null;
  review_note?: string | null;
  created_at: string;
  updated_at: string;
}
export interface AnalysisJobResponse {
  job_id: string;
  exercise_id: string;
  status: "queued" | "running" | "completed" | "failed" | "cancelled";
  stage: string;
  progress: number;
  attempts: number;
  max_attempts: number;
  cancel_requested?: boolean;
  error_code?: string | null;
  message?: string | null;
  http_status?: number | null;
  result?: Record<string, unknown> | null;
  created_at: string;
  started_at?: string | null;
  completed_at?: string | null;
  engine_version?: string | null;
  model_version?: string | null;
}
export interface AppointmentCreate {
  patient_id: string;
  therapist_user_id: string;
  service_id?: string | null;
  starts_at: string;
  ends_at: string;
  delivery_mode?: "video" | "in_person";
}
export interface AppointmentJoinResponse {
  appointment_id: string;
  room_url: string;
  meeting_token: string;
  expires_at: string;
}
export interface AppointmentSlot {
  starts_at: string;
  ends_at: string;
}
export interface AppointmentSummary {
  appointment_id: string;
  patient_id: string;
  therapist_user_id: string;
  starts_at: string;
  ends_at: string;
  status: "scheduled" | "confirmed" | "completed" | "cancelled" | "no_show";
  delivery_mode: "video" | "in_person";
  payment_status: string;
  can_join?: boolean;
}
export interface AppointmentUpdate {
  starts_at?: string | null;
  ends_at?: string | null;
  status?: "scheduled" | "confirmed" | "completed" | "cancelled" | "no_show" | null;
  cancellation_reason?: string | null;
}
export interface AuthMessageResponse {
  status?: string;
  message: string;
}
export interface AvailabilityCreate {
  weekday: number;
  start_minute: number;
  end_minute: number;
  timezone_name?: string;
}
export interface AvailabilityDetail {
  weekday: number;
  start_minute: number;
  end_minute: number;
  timezone_name?: string;
  availability_id: string;
  therapist_user_id: string;
  is_active: boolean;
}
export interface AvailabilitySlots {
  therapist_user_id: string;
  date: string;
  slots: Array<AppointmentSlot>;
}
export interface CarePlanItem {
  plan_title?: string | null;
  created_by_name?: string | null;
  item_id: string;
  exercise_id: string;
  sets: number;
  reps: number;
  duration_minutes?: number | null;
  rest_interval_seconds?: number | null;
  tempo?: string | null;
  instructions?: string | null;
  precautions?: string | null;
  target_rom_degrees?: number | null;
  target_score?: number | null;
  requested_media_upload?: boolean;
  requires_ai_analysis?: boolean;
  completion_status?: "completed" | "partial" | "not_completed" | null;
  pain_before?: number | null;
  pain_after?: number | null;
  difficulty?: number | null;
  fatigue?: number | null;
  perceived_exertion?: number | null;
  symptoms_changed?: boolean;
  stopped_due_to_symptoms?: boolean;
  symptom_flags?: Array<"pain_increase" | "dizziness" | "faintness" | "unusual_shortness_of_breath" | "chest_discomfort" | "new_numbness_or_weakness" | "instability" | "other">;
  response_state?: "not_assessed" | "within_reported_tolerance" | "clinical_follow_up";
  supportive_instruction?: string | null;
  clinician_review_required?: boolean;
  reviewed_at?: string | null;
  patient_comment?: string | null;
  analysis_session_id?: string | null;
}
export interface ClinicalNoteCreate {
  summary: string;
  recommendations?: string | null;
  patient_visible?: boolean;
}
export interface ClinicalNoteDetail {
  summary: string;
  recommendations?: string | null;
  patient_visible?: boolean;
  note_id: string;
  appointment_id: string;
  therapist_user_id: string;
  created_at: string;
  updated_at: string;
  author_name?: string | null;
}
export interface ConsentRecord {
  consent_type: string;
  accepted: boolean;
  accepted_at?: string | null;
  version: string;
}
export interface CurrentUserResponse {
  user_id: string;
  username?: string | null;
  email: string;
  full_name?: string | null;
  role: UserRole;
  is_active: boolean;
  is_verified: boolean;
  account_status?: string;
  is_protected?: boolean;
  permissions?: Array<string>;
  created_at: string;
}
export interface DetectedIssueSchema {
  issue_code: string;
  severity?: string | null;
  message?: string | null;
}
export interface EmailRequest {
  email: string;
}
export interface ExercisePlanCreate {
  title: string;
  notes?: string | null;
  start_date?: string | null;
  end_date?: string | null;
  items: Array<ExercisePlanItemCreate>;
}
export interface ExercisePlanDetail {
  created_by_name?: string | null;
  plan_id: string;
  patient_id: string;
  created_by_user_id?: string | null;
  title: string;
  notes?: string | null;
  status: "active" | "paused" | "completed";
  start_date?: string | null;
  end_date?: string | null;
  created_at: string;
  updated_at: string;
  items?: Array<ExercisePlanItemDetail>;
}
export interface ExercisePlanItemCreate {
  exercise_id: string;
  sets: number;
  reps: number;
  days_per_week: number;
  instructions?: string | null;
  duration_minutes?: number | null;
  rest_interval_seconds?: number | null;
  tempo?: string | null;
  precautions?: string | null;
  target_rom_degrees?: number | null;
  target_score?: number | null;
  schedule_days?: Array<number>;
  requested_media_upload?: boolean;
  requires_ai_analysis?: boolean;
}
export interface ExercisePlanItemDetail {
  exercise_id: string;
  sets: number;
  reps: number;
  days_per_week: number;
  instructions?: string | null;
  duration_minutes?: number | null;
  rest_interval_seconds?: number | null;
  tempo?: string | null;
  precautions?: string | null;
  target_rom_degrees?: number | null;
  target_score?: number | null;
  schedule_days?: Array<number>;
  requested_media_upload?: boolean;
  requires_ai_analysis?: boolean;
  item_id: string;
  sort_order: number;
  status?: "active" | "replaced" | "completed";
}
export interface ExercisePlanStatusUpdate {
  status: "active" | "paused" | "completed";
}
export interface ExerciseResponseReview {
  disposition: "contacted_patient" | "plan_modified" | "appointment_scheduled" | "referred_for_medical_review" | "reviewed_no_change";
  note?: string | null;
  clinician_attestation: boolean;
}
export interface NotificationSummary {
  notification_id: string;
  kind: string;
  title: string;
  body: string;
  action_url?: string | null;
  read_at?: string | null;
  created_at: string;
}
export interface PasswordResetRequest {
  token: string;
  new_password: string;
}
export interface PatientHealthProfile {
  emergency_contact_name?: string | null;
  emergency_contact_phone?: string | null;
  medical_summary?: string | null;
  precautions?: string | null;
  patient_id: string;
}
export interface PatientHealthProfileUpdate {
  emergency_contact_name?: string | null;
  emergency_contact_phone?: string | null;
  medical_summary?: string | null;
  precautions?: string | null;
}
export interface PatientTodayResponse {
  patient_id: string;
  date: string;
  plan_title?: string | null;
  plan_items?: Array<CarePlanItem>;
  upcoming_appointment?: AppointmentSummary | null;
  unread_notifications?: number;
  adherence_percent_7d?: number | null;
  average_pain_7d?: number | null;
  completed_count_7d?: number;
  partial_count_7d?: number;
  missed_count_7d?: number;
}
export interface ProgressReportCreateResponse {
  progress_report_id: string;
  download_url: string;
  shared_with_patient: boolean;
}
export interface ProgressReportSummary {
  progress_report_id: string;
  period_start: string;
  period_end: string;
  created_at: string;
  download_url: string;
}
export interface SessionDetail {
  session_id: string;
  plan_item_id?: string | null;
  exercise_id: string;
  exercise_display_name: string;
  status: string;
  created_at: string;
  total_reps?: number | null;
  movement_score?: number | null;
  analysis_confidence_level?: string | null;
  pose_quality_level?: string | null;
  detected_issues?: Array<string>;
  report_download_url?: string | null;
  overlay_preview_url?: string | null;
  error_code?: string | null;
  message?: string | null;
  updated_at: string;
  source_filename?: string | null;
  video_duration_sec?: number | null;
  rep_count_confidence?: number | null;
  analysis_confidence_score?: number | null;
  pose_quality_score?: number | null;
  summary?: string | null;
  limitations?: Array<string>;
  feedback?: Array<string>;
  score_breakdown?: Record<string, unknown> | null;
  input_validity?: Record<string, unknown> | null;
  ml_prediction?: Record<string, unknown> | null;
  report_id?: string | null;
  overlay_id?: string | null;
  overlay_download_url?: string | null;
  metrics?: Array<SessionMetricSchema>;
  issue_details?: Array<DetectedIssueSchema>;
}
export interface SessionListResponse {
  items: Array<SessionSummary>;
  total: number;
  limit: number;
  offset: number;
}
export interface SessionMetricSchema {
  metric_name: string;
  metric_value_float?: number | null;
  metric_value_text?: string | null;
  unit?: string | null;
}
export interface SessionSummary {
  session_id: string;
  plan_item_id?: string | null;
  exercise_id: string;
  exercise_display_name: string;
  status: string;
  created_at: string;
  total_reps?: number | null;
  movement_score?: number | null;
  analysis_confidence_level?: string | null;
  pose_quality_level?: string | null;
  detected_issues?: Array<string>;
  report_download_url?: string | null;
  overlay_preview_url?: string | null;
}
export interface TokenRequest {
  token: string;
}
export interface TokenResponse {
  access_token: string;
  token_type?: string;
  expires_in: number;
  user: UserSummary;
}
export interface UserLoginRequest {
  email: string;
  password: string;
}
export interface UserRegisterRequest {
  username: string;
  email: string;
  password: string;
  full_name: string;
  role?: UserRole;
  accepted_terms?: boolean;
  accepted_privacy?: boolean;
}
export type UserRole = "super_admin" | "admin" | "therapist" | "patient" | "support" | "researcher_demo";
export interface UserSummary {
  user_id: string;
  username?: string | null;
  email: string;
  full_name?: string | null;
  role: UserRole;
  is_active: boolean;
  is_verified: boolean;
  account_status?: string;
  is_protected?: boolean;
  permissions?: Array<string>;
}
