import { useRef, useState } from "react";
import { Pressable, StyleSheet, Switch, Text, View } from "react-native";
import Ionicons from "@expo/vector-icons/Ionicons";
import * as ImagePicker from "expo-image-picker";
import { useLocalSearchParams, useRouter } from "expo-router";

import { analyzeExercise } from "@/src/api/analysis";
import { AnalysisSteps, SectionTitle } from "@/src/components/GuidedUI";
import { Body, Card, PrimaryButton, Screen } from "@/src/components/UI";
import { PermissionState, UploadErrorState, VideoPreviewCard } from "@/src/components/UploadStates";
import { UploadProgress } from "@/src/components/UploadProgress";
import { APP_ENV } from "@/src/config/env";
import { colors } from "@/src/config/theme";
import { useAnalysis } from "@/src/context/AnalysisContext";
import { useAuth } from "@/src/context/AuthContext";
import { useExerciseMetadata } from "@/src/hooks/useExerciseMetadata";
import type { MobileVideo } from "@/src/types/analysis";
import { canSubmitUpload, createUploadSubmissionGuard, MISSING_VIDEO_MESSAGE, STAGING_UPLOAD_AUTH_MESSAGE, validateSelectedVideo } from "@/src/utils/uploadValidation";

function toVideo(asset: ImagePicker.ImagePickerAsset): MobileVideo { const extension = asset.fileName?.split(".").pop()?.toLowerCase() || "mp4"; return { uri: asset.uri, name: asset.fileName || `movement-${Date.now()}.${extension}`, type: asset.mimeType || (extension === "mov" ? "video/quicktime" : "video/mp4"), size: asset.fileSize, duration: asset.duration ?? undefined }; }

export default function UploadScreen() {
  const { id, source } = useLocalSearchParams<{ id: string; source?: string }>(); const router = useRouter(); const analysis = useAnalysis(); const { user } = useAuth(); const { exercise: metadata } = useExerciseMetadata(id);
  const [video, setVideo] = useState<MobileVideo | null>(analysis.video); const [saveSession, setSaveSession] = useState(false); const [includeOverlay, setIncludeOverlay] = useState(false); const [generateReport, setGenerateReport] = useState(false); const [showOptions, setShowOptions] = useState(false); const [progress, setProgress] = useState(0); const [busy, setBusy] = useState(false); const [uploadError, setUploadError] = useState(""); const [deniedPermission, setDeniedPermission] = useState<"camera" | "library" | null>(null);
  const abortRef = useRef<AbortController | null>(null); const submissionGuard = useRef(createUploadSubmissionGuard()).current;
  function accept(asset?: ImagePicker.ImagePickerAsset) { if (!asset) return; const selected = toVideo(asset); const validationError = validateSelectedVideo(selected); if (validationError) { setUploadError(validationError); return; } setVideo(selected); analysis.setVideo(selected); setUploadError(""); setDeniedPermission(null); }
  async function pickVideo() { const permission = await ImagePicker.requestMediaLibraryPermissionsAsync(); if (!permission.granted) { setDeniedPermission("library"); setUploadError(""); return; } const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ["videos"], allowsEditing: false, quality: 0.8 }); if (!result.canceled) accept(result.assets[0]); }
  async function recordVideo() { const permission = await ImagePicker.requestCameraPermissionsAsync(); if (!permission.granted) { setDeniedPermission("camera"); setUploadError(""); return; } const result = await ImagePicker.launchCameraAsync({ mediaTypes: ["videos"], videoMaxDuration: 60, quality: 0.8 }); if (!result.canceled) accept(result.assets[0]); }
  async function submit() { if (!video) { setUploadError(MISSING_VIDEO_MESSAGE); return; } if (APP_ENV === "staging" && !user) { setUploadError(STAGING_UPLOAD_AUTH_MESSAGE); return; } if (!canSubmitUpload(video, busy) || !id || !submissionGuard.tryStart()) return; const controller = new AbortController(); abortRef.current = controller; setBusy(true); setProgress(0); setUploadError(""); try { const result = await analyzeExercise(id, video, { saveSession: Boolean(user && saveSession), includeOverlay, generateReport, signal: controller.signal }, setProgress); analysis.setResult(result); router.replace("/result"); } catch (requestError) { setUploadError((requestError as Error).message); if (APP_ENV === "development") console.warn("Mobile analysis request failed", { exerciseId: id, errorName: (requestError as Error).name }); } finally { abortRef.current = null; submissionGuard.finish(); setBusy(false); } }
  const exerciseName = metadata?.display_name || analysis.exercise?.display_name || id;
  return <Screen>
    <Text style={styles.title}>Review and analyze</Text><Body muted>{exerciseName}</Body><AnalysisSteps active={3} />
    {source === "recognition" && video ? <View style={styles.ready}><Ionicons name="checkmark-circle" size={22} color={colors.teal} /><View style={styles.flex}><Text style={styles.readyTitle}>Exercise confirmed</Text><Text style={styles.readyText}>The same video is ready—no second upload needed.</Text></View></View> : null}
    <SectionTitle>{video ? "Your video" : "Add your video"}</SectionTitle>
    {video ? <VideoPreviewCard video={video} /> : <View style={styles.sourceButtons}><PrimaryButton title="Record video" onPress={recordVideo} disabled={busy} /><PrimaryButton title="Choose from phone" onPress={pickVideo} secondary disabled={busy} /></View>}
    {video && !busy ? <View style={styles.changeRow}><Pressable onPress={recordVideo} style={styles.change}><Ionicons name="videocam-outline" size={18} color={colors.primary} /><Text style={styles.changeText}>Record again</Text></Pressable><Pressable onPress={pickVideo} style={styles.change}><Ionicons name="images-outline" size={18} color={colors.primary} /><Text style={styles.changeText}>Change video</Text></Pressable></View> : null}
    {deniedPermission ? <PermissionState kind={deniedPermission} onRetry={deniedPermission === "camera" ? recordVideo : pickVideo} /> : null}
    <Pressable accessibilityRole="button" accessibilityState={{ expanded: showOptions }} onPress={() => setShowOptions((value) => !value)} style={({ pressed }) => [styles.optionsHeader, pressed && styles.pressed]}><View style={styles.optionsIcon}><Ionicons name="options-outline" size={21} color={colors.text} /></View><View style={styles.flex}><Text style={styles.optionsTitle}>Analysis settings</Text><Text style={styles.optionsDetail}>Overlay, report, and saved history</Text></View><Ionicons name={showOptions ? "chevron-up" : "chevron-down"} size={20} color={colors.text} /></Pressable>
    {showOptions ? <Card><Option label="Save to history" detail={user ? "Keep this session in your protected history." : "Log in to enable session history."} value={saveSession} disabled={!user || busy} onChange={setSaveSession} /><Option label="Annotated video" detail="Create a temporary movement overlay." value={includeOverlay} disabled={busy} onChange={setIncludeOverlay} /><Option label="PDF report" detail="Create a downloadable session report." value={generateReport} disabled={busy} onChange={setGenerateReport} /></Card> : null}
    {uploadError ? <UploadErrorState message={uploadError} onRetry={submit} canRetry={Boolean(video) && !busy} /> : null}
    {busy ? <Card><Text style={styles.analyzing}>Analyzing your movement</Text><UploadProgress progress={progress} /><PrimaryButton title="Cancel" onPress={() => abortRef.current?.abort()} secondary /></Card> : null}
    <PrimaryButton title={busy ? "Analyzing…" : "Analyze movement"} onPress={submit} disabled={busy || !video} />
    <View style={styles.safety}><Ionicons name="heart-outline" size={19} color={colors.teal} /><Text style={styles.safetyText}>Stop if you feel pain, dizziness, or unusual symptoms.</Text></View>
  </Screen>;
}

function Option({ label, detail, value, disabled, onChange }: { label: string; detail: string; value: boolean; disabled: boolean; onChange: (value: boolean) => void }) { return <View style={styles.option}><View style={styles.optionText}><Text style={styles.label}>{label}</Text><Text style={styles.detail}>{detail}</Text></View><Switch value={value} disabled={disabled} onValueChange={onChange} trackColor={{ true: colors.teal }} /></View>; }
const styles = StyleSheet.create({ title: { color: colors.text, fontSize: 30, lineHeight: 36, fontWeight: "800", letterSpacing: -0.5 }, ready: { flexDirection: "row", alignItems: "center", gap: 11, padding: 14, borderRadius: 16, backgroundColor: colors.paleTeal }, readyTitle: { color: colors.text, fontSize: 14, fontWeight: "800" }, readyText: { color: colors.muted, fontSize: 12, marginTop: 2 }, flex: { flex: 1 }, sourceButtons: { gap: 9 }, changeRow: { flexDirection: "row", justifyContent: "center", gap: 22 }, change: { minHeight: 42, flexDirection: "row", alignItems: "center", gap: 6 }, changeText: { color: colors.primary, fontWeight: "800", fontSize: 13 }, optionsHeader: { minHeight: 70, borderTopWidth: 1, borderBottomWidth: 1, borderColor: colors.border, flexDirection: "row", alignItems: "center", gap: 11, paddingVertical: 10 }, optionsIcon: { width: 42, height: 42, borderRadius: 14, backgroundColor: colors.surface, alignItems: "center", justifyContent: "center" }, optionsTitle: { color: colors.text, fontSize: 15, fontWeight: "800" }, optionsDetail: { color: colors.muted, fontSize: 12, marginTop: 2 }, option: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12, paddingVertical: 6 }, optionText: { flex: 1 }, label: { color: colors.text, fontWeight: "700" }, detail: { color: colors.muted, fontSize: 12, lineHeight: 17 }, analyzing: { color: colors.text, fontSize: 16, fontWeight: "800" }, safety: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, paddingVertical: 8 }, safetyText: { flex: 1, color: colors.muted, fontSize: 12, lineHeight: 17 }, pressed: { opacity: 0.65 } });
