"""Clinically reviewable constants for the rule-based squat prototype."""

STANDING_KNEE_ANGLE_DEG = 160.0
SQUAT_DEPTH_KNEE_ANGLE_DEG = 115.0
SQUAT_ATTEMPT_KNEE_ANGLE_DEG = 140.0
TRUNK_LEAN_THRESHOLD_DEG = 35.0
KNEE_VALGUS_MARGIN_NORMALIZED = 0.035
KNEE_VALGUS_FRAME_RATIO = 0.25
LOW_CONFIDENCE_FRAME_RATIO = 0.40
INCONSISTENT_DEPTH_STD_DEG = 18.0

# Rep state-machine thresholds. These are reviewable prototype defaults, not
# clinically validated cut-offs.
MIN_DEPTH_DELTA_DEG = 35.0
MIN_REP_DURATION_SEC = 0.8
MAX_REP_DURATION_SEC = 8.0
MIN_FRAMES_BETWEEN_REPS = 10
BOTTOM_HOLD_MIN_FRAMES = 2
ANGLE_DIRECTION_EPSILON_DEG = 1.5
ANGLE_SMOOTHING_WINDOW = 5

ML_LOW_CONFIDENCE_THRESHOLD = 0.65

# Input validity gate. These protect scoring from static, incomplete, or
# insufficiently visible recordings; they are not clinical cut-offs.
MIN_POSE_DETECTED_FRAMES = 30
MIN_KNEE_ANGLE_RANGE_DEG = 30.0
MIN_HIP_ANGLE_RANGE_DEG = 20.0
MIN_VALID_REPS = 1
MIN_POSE_DETECTION_RATE = 0.50
MIN_CRITICAL_LANDMARK_VISIBILITY = 0.50
MIN_MOTION_VARIATION_DEG = 0.75
